# inventario.ini

[edge_nodes]
pi_zero_ups ansible_host=pi-zero-ups.local ansible_user=example_user

[servidores_core]
nas_ugreen ansible_host=192.168.50.2 ansible_user=example_user

[all:vars]
# Esta variable aplicará para ambos grupos (te pedirá la contraseña al ejecutar)
ansible_become_pass="{{ sudo_password }}"